### ISSUE TITLE
Suggestion: Thing text selected by default on Edit Task dialog open

### ISSUE THREAD

**Issue by zoharsnir** [one-thing-gnome/one-thing#10]
My suggestion is that when the "Edit task" dialog is opened, the text would be selected by default.

This would allow the user to immediately start typing a new "thing" and hit Enter to set it, without the need to delete delete the existing text.

It shouldn't prevent the user from clicking on any other UI element if that was his intent.

Also, thanks for a great simple add-on

**Comment by pratap-panabaka** [comment]
Hi @zoharsnir it is now implemented in `add-keybinding` branch.
