### ISSUE TITLE
Suggestion: Add support to assigning a hotkey for opening Edit Task dialog

### ISSUE THREAD

**Issue by zoharsnir** [one-thing-gnome/one-thing#11]
The suggestion is to add support to assigning a hotkey to opening the Edit Task dialog.

Together with https://github.com/one-thing-gnome/one-thing/issues/10 this would allow for the main user flow of this extention to be minimal effort for keyboard centric users:

To change the Thing, from anywhere, you'd only need to type `<hotkey>` `<Text for new Thing>` `[Enter]`

Also, thanks for a great simple add-on

**Comment by pratap-panabaka** [comment]
@zoharsnir there is `add-keybinding` branch with this repo. you can try that for hot key `Alt+W`. You may need to CTRL+A and then text for new thing.

Thanks!

**Comment by pratap-panabaka** [comment]
@zoharsnir when the popup is opened, All the text is now selected so that you can type your new thing with

1. `Alt+W`
2. type newThing
3. Enter
