### ISSUE TITLE
Compatibility with Gnome 44

### ISSUE THREAD

**Issue by adrm** [one-thing-gnome/one-thing#13]
Just updated to Fedora 38 with Gnome 44 and the extension stopped working.

**Comment by qwertychouskie** [comment]
Not sure why this is closed, as it still affects the current release.

**Comment by kra-mo** [comment]
Its fixed in git, I just can't reach @dantehemerson who maintains the extensions.gnome.org releases.

**Comment by dantehemerson** [comment]
@adrm @kra-mo I just released the the version with the latest changes and now it supports Gnome 44.
