### ISSUE TITLE
Update for gnome shell 46?

### ISSUE THREAD

**Issue by ghost** [one-thing-gnome/one-thing#18]
Can this please be updated for gnome shell 46?

**Comment by dmhowcroft** [comment]
I've also been waiting for this--it's so useful to have this little note to self in my status bar!

**Comment by dantehemerson** [comment]
Hi @reahari @dmhowcroft I released a new version that supports `v46`.

**Comment by dmhowcroft** [comment]
Thanks! I just updated and get the following error:
`TypeError: Main.uiGroup.add_actor is not a function`.

The error is displayed when I'm in the extensions settings app in Gnome, and so Gnome does not let the extension run.

**Comment by dantehemerson** [comment]
Hi @dmhowcroft I didn't noticed that, but I just fixed it. Can you install the latest version? Let me know if you still have issues.

**Comment by dmhowcroft** [comment]
Looks like it's working for me now! Thanks :)
----
David M. Howcroft
https://www.davehowcroft.com
