### ISSUE TITLE
Update for GNOME 47?

### ISSUE THREAD

**Issue by ghost** [one-thing-gnome/one-thing#23]
Can you please update this for GNOME 47?

**Comment by emacnabber** [comment]
Yes, this would great if you could. Thanks!

**Comment by Fredoah** [comment]
Hi@All,
My proposition :

For Gnome 47 compatibility :
Go ---> `/home/"user"/.local/share/gnome-shell/extensions/one-thing@github.com/`
Edit metadata.json and Add 47 :
    

```
 "shell-version": [
          "45",
          "46",
          "47"
```
Save and disconnect / Reconnect session
Tested and approved :)

**Comment by dantehemerson** [comment]
Hi @reahari I added support for gnome shell v47.
