### ISSUE TITLE
Suggestion: show how to set one-thing value in README

### ISSUE THREAD

**Issue by canadaduane** [one-thing-gnome/one-thing#9]
This is such a ONE-derful extension, thank you!

I am using it daily, and have connected it to my workflow. Here is how I set the value in the menu bar from the command line:

```
dconf write /org/gnome/shell/extensions/one-thing/thing-value "'My todo'"
```

I'm using it in Wayland to copy the clipboard to One Thing like so:

```
dconf write /org/gnome/shell/extensions/one-thing/thing-value "'$(wl-paste|sed "s/'/\\\'/g")'"
```

Perhaps others can benefit from this also. Thanks!

**Comment by bartkl** [comment]
Thanks a lot. I was wrestling with `gsettings` and couldn't get it done. This worked for me!

**Comment by pratap-panabaka** [comment]
Hi @canadaduane and @bartkl It is added to the branch `add-keybinding`. Once the PR is approved, the branch will be merged to `main`
